//#############################################
//## file: GW2Parser.java
//## Generated by Byacc/j
//#############################################
package Parsing;

/**
 * BYACC/J Semantic Value for parser: GW2Parser
 * This class provides some of the functionality
 * of the yacc/C 'union' directive
 */
public class GW2ParserVal
{
/**
 * integer value of this 'union'
 */
public int ival;

/**
 * double value of this 'union'
 */
public double dval;

/**
 * string value of this 'union'
 */
public String sval;

/**
 * object value of this 'union'
 */
public Object obj;

//#############################################
//## C O N S T R U C T O R S
//#############################################
/**
 * Initialize me without a value
 */
public GW2ParserVal()
{
}
/**
 * Initialize me as an int
 */
public GW2ParserVal(int val)
{
  ival=val;
}

/**
 * Initialize me as a double
 */
public GW2ParserVal(double val)
{
  dval=val;
}

/**
 * Initialize me as a string
 */
public GW2ParserVal(String val)
{
  sval=val;
}

/**
 * Initialize me as an Object
 */
public GW2ParserVal(Object val)
{
  obj=val;
}
}//end class

//#############################################
//## E N D    O F    F I L E
//#############################################
